name: Generate Redoc API Documentation

on:
  push:
    paths:
      - '**.yaml' # Replace with the path to your Swagger spec file

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # You can specify the Node.js version here

      - name: Install Redocly CLI
        run: npm install @redocly/cli -g

      - name: Generate API documentation
        run: redocly build-docs SwaggerInventory.yaml -o index2.html --theme.openapi.disableSearch
      - name: Commit documentation
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: 'Update documentation'
          add: '*.md'
          github_token: ${{ secrets.GIT_ACTION }}
