name: Generate Redoc API Documentation

on:
  push:
    paths:
      - '**.yaml' # Replace with the path to your Swagger spec file

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # You can specify the Node.js version here

      - name: Install Redocly CLI
        run: npm install -g redoc-cli

      - name: Generate API documentation
        run: redoc-cli bundle https://raw.githubusercontent.com/guruprakashchinnasamy/poc/main/SwaggerInventory.yaml -o docs/index2.html
